# https://github.com/symfony-doge/gogs-docker-compose
version: '2'

services:
    app:
        build:
            context: .
        networks:
            - gogs_db
        depends_on:
            - db
        ports:
            - "9090:3000"
            - "9022:22"
        volumes:
            - app_data:/data

    db:
        image: postgres:11
        networks:
            - gogs_db
        environment:
            POSTGRES_DB: gogs
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

networks:
    gogs_db:
        driver: bridge

volumes:
    app_data:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/data/app
            o: bind
    db_data:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/data/db/data
            o: bind
